language: shell
dist: bionic
sudo: enabled
os: linux
virt: vm
group: edge
arch:
  - arm64-graviton2
#  - amd64

env:
  global:
addons:
  snaps:
    - name: snapcraft
      channel: stable
      confinement: classic

install:

script:
  - snapcraft --destructive-mode
after_failure:
  #- sudo journalctl -u snapd
deploy:
  - provider: snap
    snap: ci*.snap
    channel: edge
    skip_cleanup: true
    on:
      all_branches: true
